### PR TITLE
Update unit test in local PC

### PR DESCRIPTION
**Pull request by sy1124kim**
Add gmock static library(arm).
Add g++ compiler option.

googletest : https://github.com/dockzen/googletest.git

Signed-off-by: sy1124.kim <sy1124.kim@samsung.com>

### CODE REVIEW

**Comment by wansuyoo** [comment]
Is anyone there knows how can expand the window of "Files changed" at github?
I can't see the changes of some lines over the window view.
Anyway, I'll see this PR from git branch.

**Comment by jiehwan** [comment]
@wansuyoo, i can see diff sources.. it may be issue of your env. (however, *.a file shows nothing. it is correct)

**Comment by jiehwan** [comment]
during CXX building.. error are occurred.

**Comment by jiehwan** [comment]
still error..

**Comment by sy1124kim** [comment]
My mistake!! 
Add include folder of gmock and gtest in path(src/lib/install/include).

**Comment by jiehwan** [comment]
link errors are occurred (same for amd64 and arm)

## link error in amd64
[ 93%] Linking CXX executable gtest-dockzen_launcher
CMakeFiles/gtest-dockzen_launcher.dir/dockzen-launcher_DockerForm.cpp.o: In function `testing::AssertionResult testing::internal::CmpHelperEQFailure<docker_status_e, int>(char const*, char const*, docker_status_e const&, int const&)':
dockzen-launcher_DockerForm.cpp:(.text._ZN7testing8internal18CmpHelperEQFailureI15docker_status_eiEENS_15AssertionResultEPKcS5_RKT_RKT0_[_ZN7testing8internal18CmpHelperEQFailureI15docker_status_eiEENS_15AssertionResultEPKcS5_RKT_RKT0_]+0x87): undefined reference to `testing::internal::EqFailure(char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
CMakeFiles/gtest-dockzen_launcher.dir/dockzen-launcher_DockerForm.cpp.o: In function `testing::AssertionResult testing::internal::CmpHelperEQFailure<int, int>(char const*, char const*, int const&, int const&)':
dockzen-launcher_DockerForm.cpp:(.text._ZN7testing8internal18CmpHelperEQFailureIiiEENS_15AssertionResultEPKcS4_RKT_RKT0_[_ZN7testing8internal18CmpHelperEQFailureIiiEENS_15AssertionResultEPKcS4_RKT_RKT0_]+0x87): undefined reference to `testing::internal::EqFailure(char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
CMakeFiles/gtest-dockzen_launcher.dir/dockzen-launcher_DZL_Setting.cpp.o: In function `testing::AssertionResult::AppendMessage(testing::Message const&)':
dockzen-launcher_DZL_Setting.cpp:(.text._ZN7testing15AssertionResult13AppendMessageERKNS_7MessageE[_ZN7testing15AssertionResult13AppendMessageERKNS_7MessageE]+0x73): undefined reference to `testing::Message::GetString[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
unittest/CMakeFiles/gtest-dockzen_launcher.dir/build.make:276: recipe for target 'unittest/gtest-dockzen_launcher' failed
make[2]: *** [unittest/gtest-dockzen_launcher] Error 1
CMakeFiles/Makefile2:195: recipe for target 'unittest/CMakeFiles/gtest-dockzen_launcher.dir/all' failed
make[1]: *** [unittest/CMakeFiles/gtest-dockzen_launcher.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sy1124kim** [comment]
@jiehwan ,
This error is caused by different g++ version.
You can rebuild googletest(https://github.com/dockzen/googletest.git) library and use it.

(sy1124.kim) linux computer g++ version : g++  4.8.4
(jiehwan) linux computer g++ version : g++ 5.4.0

**Comment by jiehwan** [comment]
@sy1124kim. you mentioned that the library (g++ 5.4.0) is working all of ubuntu versions.
as we don't need to manage googletest, it will be better to upload the library(g++ 5.4.0) into our sources.
please update into the launcher.

**Comment by sy1124kim** [comment]
Added build option for unit test. 
In case of unit test, you should be install gtest(https://github.com/dockzen/googletest.git) library into Linux Host PC.
ex)
$ build.sh -t 
or 
$ build.sh -t arm

**Comment by jiehwan** [comment]
1. request to edit README.md file to explain how to build for test..
it should include build direction for required googletest package and explain test sequence.
2. question for test executable output file.. 
after "./build.sh arm -t" i can't find whereis gtestxxx unit test file.
where is ? (i can see the output for the case of amd64 in build/amd/)

**Comment by sy1124kim** [comment]
Updated README.md

**Comment by Namsulee** [comment]
Update .gitingore filde not to be shown int untracked file after building.
I can see 2 files after build that you provide.
unittest/dockzen_api/gtest-docken_api
unittest/gtest-dockzen_launcher

You can check it when you type 'git status' after building.

**Comment by sy1124kim** [comment]
@Namsulee, Updated .gitignore file.

**Pull request merged**
